### ISSUE TITLE
crashes and wont let me join server when holding a map

### ISSUE THREAD

**Issue by kbkpenguin** [ChosenArchitect/ChosensModdedAdventure#39]
**Describe the bug**
while holding a map it kicked me when trying to open a chest and after trying to rejoin i kept getting an error code

**To Reproduce**
1. hold map 
2. open chest

**Modpack version**
->0.2.2

**Modpack Launcher Used**
-> ftb launcher

[02:02:33] [Server thread/WARN] [minecraft/ServerConnectionListener]: 
net.minecraft.ReportedException: Ticking player
        at net.minecraft.server.level.ServerPlayer.m_9240_(ServerPlayer.java:530) ~[server-1.20.1-20230612.114412-srg.jar%23645!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:yungsapi.mixins.json:ServerPlayerEntityTickMixin,pl:mixin:APP:servercore.common.mixins.json:optimizations.players.ServerPlayerMixin,pl:mixin:APP:craterlib.mixins.json:events.ServerPlayerMixin,pl:mixin:APP:ars_nouveau.mixins.json:camera.ANServerPlayerMixin,pl:mixin:APP:netherportalfix.mixins.json:ServerPlayerMixin,pl:mixin:APP:netherportalfix.mixins.json:ForgeServerPlayerMixin,pl:mixin:APP:vmp.mixins.json:chunk.loading.async_chunk_on_player_login.MixinServerPlayerEntity,pl:mixin:APP:vmp.mixins.json:playerwatching.MixinServerPlayerEntity,pl:mixin:APP:vmp.mixins.json:playerwatching.optimize_nearby_entity_tracking_lookups.MixinServerPlayerEntity,pl:mixin:A}
        at net.minecraft.server.network.ServerGamePacketListenerImpl.m_9933_(ServerGamePacketListenerImpl.java:262) ~[server-1.20.1-20230612.114412-srg.jar%23645!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:modernfix-forge.mixins.json:bugfix.forge_vehicle_packets.ServerGamePacketListenerImplMixin,pl:mixin:APP:supplementaries-common.mixins.json:ServerGamePacketListenerMixin,pl:mixin:APP:servercore.common.mixins.json:features.misc.ServerGamePacketListenerImplMixin,pl:mixin:APP:flightlib.mixins.json:ServerGamePacketListenerImplAccessor,pl:mixin:APP:craterlib.mixins.json:events.ServerGamePacketListenerImplMixin,pl:mixin:APP:hangglider.common.mixins.json:accessor.ServerGamePacketListenerImplAccessor,pl:mixin:APP:vmp.mixins.json:access.IServerPlayNetworkHandler,pl:mixin:APP:vmp.mixins.json:chunk.loading.async_chunk_on_player_login.MixinServerPlayNetworkHandler,pl:mixin:A}
        at net.minecraft.network.Connection.m_129483_(Connection.java:263) ~[server-1.20.1-20230612.114412-srg.jar%23645!/:?] {re:mixin,re:classloading,pl:mixin:APP:vmp.mixins.json:access.IClientConnection,pl:mixin:APP:vmp.mixins.json:networking.avoid_deadlocks.MixinClientConnection,pl:mixin:APP:vmp.mixins.json:networking.eventloops.MixinClientConnection,pl:mixin:APP:vmp.mixins.json:networking.no_flush.MixinClientConnection,pl:mixin:A}
        at net.minecraft.server.network.ServerConnectionListener.m_9721_(ServerConnectionListener.java:142) ~[server-1.20.1-20230612.114412-srg.jar%23645!/:?] {re:mixin,re:classloading,pl:mixin:APP:vmp.mixins.json:networking.eventloops.MixinServerNetworkIo,pl:mixin:A}
        at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:907) ~[server-1.20.1-20230612.114412-srg.jar%23645!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:servercore.common.mixins.json:features.misc.MinecraftServerMixin,pl:mixin:APP:modernfix-common.mixins.json:perf.dedicated_reload_executor.MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:servercore.common.mixins.json:MinecraftServerMixin,pl:mixin:APP:ae2.mixins.json:spatial.MinecraftServerMixin,pl:mixin:APP:crafttweaker.mixins.json:common.access.server.AccessMinecraftServer,pl:mixin:APP:citadel.mixins.json:MinecraftServerMixin,pl:mixin:A}
        at net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServer.java:273) ~[server-1.20.1-20230612.114412-srg.jar%23645!/:?] {re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
        at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:814) ~[server-1.20.1-20230612.114412-srg.jar%23645!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:servercore.common.mixins.json:features.misc.MinecraftServerMixin,pl:mixin:APP:modernfix-common.mixins.json:perf.dedicated_reload_executor.MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:servercore.common.mixins.json:MinecraftServerMixin,pl:mixin:APP:ae2.mixins.json:spatial.MinecraftServerMixin,pl:mixin:APP:crafttweaker.mixins.json:common.access.server.AccessMinecraftServer,pl:mixin:APP:citadel.mixins.json:MinecraftServerMixin,pl:mixin:A}
        at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:661) ~[server-1.20.1-20230612.114412-srg.jar%23645!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:servercore.common.mixins.json:features.misc.MinecraftServerMixin,pl:mixin:APP:modernfix-common.mixins.json:perf.dedicated_reload_executor.MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:servercore.common.mixins.json:MinecraftServerMixin,pl:mixin:APP:ae2.mixins.json:spatial.MinecraftServerMixin,pl:mixin:APP:crafttweaker.mixins.json:common.access.server.AccessMinecraftServer,pl:mixin:APP:citadel.mixins.json:MinecraftServerMixin,pl:mixin:A}
        at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:251) ~[server-1.20.1-20230612.114412-srg.jar%23645!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:servercore.common.mixins.json:features.misc.MinecraftServerMixin,pl:mixin:APP:modernfix-common.mixins.json:perf.dedicated_reload_executor.MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:servercore.common.mixins.json:MinecraftServerMixin,pl:mixin:APP:ae2.mixins.json:spatial.MinecraftServerMixin,pl:mixin:APP:crafttweaker.mixins.json:common.access.server.AccessMinecraftServer,pl:mixin:APP:citadel.mixins.json:MinecraftServerMixin,pl:mixin:A}
        at java.lang.Thread.run(Thread.java:833) ~[?:?] {re:mixin}
Caused by: java.util.ConcurrentModificationException
        at java.util.HashMap$HashIterator.nextNode(HashMap.java:1597) ~[?:?] {}
        at java.util.HashMap$ValueIterator.next(HashMap.java:1625) ~[?:?] {}
        at net.minecraft.world.level.saveddata.maps.MapItemSavedData.handler$bla000$checkBanners(MapItemSavedData.java:1873) ~[server-1.20.1-20230612.114412-srg.jar%23645!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
        at net.minecraft.world.level.saveddata.maps.MapItemSavedData.m_77930_(MapItemSavedData.java:493) ~[server-1.20.1-20230612.114412-srg.jar%23645!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
        at net.minecraft.world.item.MapItem.m_42893_(MapItem.java:175) ~[server-1.20.1-20230612.114412-srg.jar%23645!/:?] {re:mixin,re:classloading,pl:mixin:APP:supplementaries-common.mixins.json:MapItemMixin,pl:mixin:APP:servercore.common.mixins.json:optimizations.sync_loads.MapItemMixin,pl:mixin:APP:moonlight-common.mixins.json:MapItemMixin,pl:mixin:APP:asynclocator.mixins.json:MapItemAccess,pl:mixin:A}
        at net.minecraft.world.item.MapItem.m_6883_(MapItem.java:313) ~[server-1.20.1-20230612.114412-srg.jar%23645!/:?] {re:mixin,re:classloading,pl:mixin:APP:supplementaries-common.mixins.json:MapItemMixin,pl:mixin:APP:servercore.common.mixins.json:optimizations.sync_loads.MapItemMixin,pl:mixin:APP:moonlight-common.mixins.json:MapItemMixin,pl:mixin:APP:asynclocator.mixins.json:MapItemAccess,pl:mixin:A}
        at net.minecraft.world.item.ItemStack.m_41666_(ItemStack.java:481) ~[server-1.20.1-20230612.114412-srg.jar%23645!/:?] {re:mixin,xf:fml:forge:itemstack,re:classloading,xf:fml:forge:itemstack,pl:mixin:APP:apotheosis.mixins.json:ItemStackMixin,pl:mixin:APP:attributeslib.mixins.json:ItemStackMixin,pl:mixin:APP:mixins.mlib.json:MixinItemStack,pl:mixin:APP:insanelib.mixins.json:ItemStackMixin,pl:mixin:APP:placebo.mixins.json:ItemStackMixin,pl:mixin:APP:itemfilters-common.mixins.json:ItemStackMixin,pl:mixin:APP:fastsuite.mixins.json:ItemStackMixin,pl:mixin:APP:forbidden_arcanus.mixins.json:ItemStackMixin,pl:mixin:A}
        at net.minecraft.world.entity.player.Inventory.m_36068_(Inventory.java:229) ~[server-1.20.1-20230612.114412-srg.jar%23645!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:moonlight-common.mixins.json:InventoryMixin,pl:mixin:A}
        at net.minecraft.world.entity.player.Player.m_8107_(Player.java:499) ~[server-1.20.1-20230612.114412-srg.jar%23645!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:enderzoology.common.mixins.json:PlayerMixin,pl:mixin:APP:darkutils.mixins.json:AccessorPlayer,pl:mixin:APP:darkutils.mixins.json:MixinPlayer,pl:mixin:APP:supplementaries.mixins.json:PlayerProjectileMixin,pl:mixin:APP:attributeslib.mixins.json:PlayerMixin,pl:mixin:APP:geore.mixins.json:PlayerMixin,pl:mixin:APP:ars_nouveau.mixins.json:elytra.ElytraPlayerMixin,pl:mixin:APP:mixins.mlib.json:MixinPlayer,pl:mixin:APP:insanelib.mixins.json:PlayerMixin,pl:mixin:APP:hangglider.common.mixins.json:PlayerMixin,pl:mixin:APP:easymagic.common.mixins.json:accessor.PlayerAccessor,pl:mixin:APP:comforts.mixins.json:AccessorPlayer,pl:mixin:APP:friendsandfoes-common.mixins.json:PlayerEntityMixin,pl:mixin:APP:forbidden_arcanus.mixins.json:PlayerMixin,pl:mixin:APP:betterarcheology.mixins.json:ElytraStartupMixin,pl:mixin:APP:create_enchantment_industry.mixins.json:PlayerMixin,pl:mixin:A}
        at net.minecraft.world.entity.LivingEntity.m_8119_(LivingEntity.java:2292) ~[server-1.20.1-20230612.114412-srg.jar%23645!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:apotheosis.mixins.json:LivingEntityInvoker,pl:mixin:APP:apotheosis.mixins.json:LivingEntityMixin,pl:mixin:APP:apotheosis.mixins.json:MHFMixinLivingEntity,pl:mixin:APP:mixins.shetiphiancore.json:SPC_ThinBlockHandler$_LivingEntity,pl:mixin:APP:supplementaries-common.mixins.json:LivingEntityMixin,pl:mixin:APP:servercore.common.mixins.json:features.activation_range.inactive_ticks.LivingEntityMixin,pl:mixin:APP:curios.mixins.json:MixinLivingEntity,pl:mixin:APP:attributeslib.mixins.json:LivingEntityMixin,pl:mixin:APP:caelus.mixins.json:MixinLivingEntity,pl:mixin:APP:craterlib.mixins.json:events.LivingEntityMixin,pl:mixin:APP:ars_nouveau.mixins.json:elytra.MixinLivingEntity,pl:mixin:APP:ars_nouveau.mixins.json:perks.PerkLivingEntity,pl:mixin:APP:ars_nouveau.mixins.json:LivingAccessor,pl:mixin:APP:mixins.mlib.json:MixinLivingEntity,pl:mixin:APP:netherportalfix.mixins.json:LivingEntityAccessor,pl:mixin:APP:insanelib.mixins.json:LivingEntityMixin,pl:mixin:APP:citadel.mixins.json:LivingEntityMixin,pl:mixin:APP:bookshelf.common.mixins.json:accessors.entity.AccessorLivingEntity,pl:mixin:APP:bookshelf.common.mixins.json:patches.entity.MixinLivingEntity,pl:mixin:APP:friendsandfoes-common.mixins.json:BlazeLivingEntityMixin,pl:mixin:APP:mixins.enderio.json:LivingEntityMixin,pl:mixin:APP:betterarcheology.mixins.json:TorrentTotemItemTickMixin,pl:mixin:APP:create.mixins.json:CustomItemUseEffectsMixin,pl:mixin:APP:create.mixins.json:LavaSwimmingMixin,pl:mixin:APP:create.mixins.json:accessor.LivingEntityAccessor,pl:mixin:A}
        at net.minecraft.world.entity.player.Player.m_8119_(Player.java:241) ~[server-1.20.1-20230612.114412-srg.jar%23645!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:enderzoology.common.mixins.json:PlayerMixin,pl:mixin:APP:darkutils.mixins.json:AccessorPlayer,pl:mixin:APP:darkutils.mixins.json:MixinPlayer,pl:mixin:APP:supplementaries.mixins.json:PlayerProjectileMixin,pl:mixin:APP:attributeslib.mixins.json:PlayerMixin,pl:mixin:APP:geore.mixins.json:PlayerMixin,pl:mixin:APP:ars_nouveau.mixins.json:elytra.ElytraPlayerMixin,pl:mixin:APP:mixins.mlib.json:MixinPlayer,pl:mixin:APP:insanelib.mixins.json:PlayerMixin,pl:mixin:APP:hangglider.common.mixins.json:PlayerMixin,pl:mixin:APP:easymagic.common.mixins.json:accessor.PlayerAccessor,pl:mixin:APP:comforts.mixins.json:AccessorPlayer,pl:mixin:APP:friendsandfoes-common.mixins.json:PlayerEntityMixin,pl:mixin:APP:forbidden_arcanus.mixins.json:PlayerMixin,pl:mixin:APP:betterarcheology.mixins.json:ElytraStartupMixin,pl:mixin:APP:create_enchantment_industry.mixins.json:PlayerMixin,pl:mixin:A}
        at net.minecraft.server.level.ServerPlayer.m_9240_(ServerPlayer.java:467) ~[server-1.20.1-20230612.114412-srg.jar%23645!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:yungsapi.mixins.json:ServerPlayerEntityTickMixin,pl:mixin:APP:servercore.common.mixins.json:optimizations.players.ServerPlayerMixin,pl:mixin:APP:craterlib.mixins.json:events.ServerPlayerMixin,pl:mixin:APP:ars_nouveau.mixins.json:camera.ANServerPlayerMixin,pl:mixin:APP:netherportalfix.mixins.json:ServerPlayerMixin,pl:mixin:APP:netherportalfix.mixins.json:ForgeServerPlayerMixin,pl:mixin:APP:vmp.mixins.json:chunk.loading.async_chunk_on_player_login.MixinServerPlayerEntity,pl:mixin:APP:vmp.mixins.json:playerwatching.MixinServerPlayerEntity,pl:mixin:APP:vmp.mixins.json:playerwatching.optimize_nearby_entity_tracking_lookups.MixinServerPlayerEntity,pl:mixin:A}
        ... 9 more
-

**Comment by ChosenArchitect** [comment]
do you remember where you got this map from?

**Comment by ChosenArchitect** [comment]
same as #34
